---
# This role installs httpd

- name: Install http
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php

- name: Copy apache php conf
  copy:
   src: /tmp/php.conf
   dest: /etc/httpd/conf.d/php.conf
   owner: root
   group: root

- name: http service state
  service: name=httpd state=started enabled=yes
