---

# httpd is handled by the base-apache role upstream
- name: Install git 
  yum: name={{ item }} state=present
  with_items:
   - git

- name: Configure SELinux to allow httpd to connect
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes

- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/html/
