---
# Apply common configuration to all hosts
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  roles:
  - common

# Configure and deploy the web servers. Note that we include two roles here, 
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: webservers
  become: yes
  become_method: sudo
  become_user: root
  roles:
  - base-apache
  - web

# Configure and deploy the load balancer(s).
- hosts: lbservers
  become: yes
  become_method: sudo
  become_user: root
  roles:
  - haproxy
